runtime: nodejs16 # or another supported version

# [START vonage_env]
# The following env variables may contain sensitive information that grants
# anyone access to your Twilio account. Do not add this file to your source control.
env_variables:
  API_KEY: fceXXXXX
  API_SECRET: wvyXYYYYYYYYYYYY
  FROM_NUMBER: 44731200000
  TO_NUMBER: 819045678977