runtime: nodejs16 # or another supported version

service: voice

# [START vonage_env]
# The following env variables may contain sensitive information that grants
# anyone access to your Vonage account. Do not add this file to your source control.
env_variables:
  API_KEY: d9676457
  API_SECRET: hbPngbRUnRpdo8lb
  FROM_NUMBER: 447520649993
  TO_NUMBER: 819065185577
  VIRTUAL_NUMBER: 12013047182
  APPLICATION_ID: 3df00490-26f1-4275-b90f-800c3bf566e7
  PRIVATE_KEY_PATH: private.key